name: Continuous-Integration

# El on: seria como el trigger: de Azure Devops
on:
  push:
    branches: 
      -master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar Repo
        uses: actions/checkout@v4.1.7

      - name: Instalar Modejs
        uses: actions/setup-node@v4.0.3

      - name: Instalar dependedencias
        run: npm install
     
